### ISSUE TITLE
After deploy on Azure, no swarm mode is available

### ISSUE THREAD

**Issue by pekajota** [docker/for-azure#18]
### Expected behavior
After deploying on Azure, login to swarm-manager, issue docker node ls to check the list of managers and nodes.
### Actual behavior
An error message stating that:
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
### Steps to reproduce the behavior

  1. Deploy Docker for Azure template 
  2. Log in to swarm-manager000000
  3. docker node ls
  4. Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

Any ideas on what might be happening here?

**Comment by ddebroy** [comment]
This typically results from an incorrectly specified AppID/Password for the service principal. Can you double check those? If you invoke `docker logs $(docker ps -a | grep init | cut -d' ' -f 1)`, you may get an idea of what is wrong.

**Comment by ddebroy** [comment]
Please reopen if there are any updates/new data.

**Comment by marin42** [comment]
Hey, I have the exact same problem since yesterday, I launched docker for azure many times, created multiple Principal Agents from both cli and web interface, none working...

This is the output of docker logs:
I followed the exact same steps as op with a brand new ressource group and a brand new Principal Agent created using `docker run -ti docker4x/create-sp-azure sp-name [rg-name rg-region]
`
Can you please reopen the issue ?

```
swarm-manager000000:~$ docker logs $(docker ps -a | grep init | cut -d' ' -f 1)
#================
Start Swarm setup
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ROLE=MANAGER
PRIVATE_IP=10.0.0.5
DOCKER_FOR_IAAS_VERSION=18.03.0-ce-azure1
ACCOUNT_ID=811fd0fa-2ab7-48af-a794-973e11ad3ce0
AZURE_HOSTNAME=173b8bedf26c
CHANNEL=
EDITION_ADDON=
RESOURCE_MANAGER_ENDPOINT=
STORAGE_ENDPOINT=
ACTIVE_DIRECTORY_ENDPOINT=
SERVICE_MANAGEMENT_ENDPOINT=
#================
container-logs
kick off logger container
Unable to find image 'docker4x/logger-azure:18.03.0-ce-azure1' locally
18.03.0-ce-azure1: Pulling from docker4x/logger-azure
550fe1bea624: Already exists
f039c9699f16: Pull complete
0f838b5dd9e7: Pull complete
61fdcf1e775d: Pull complete
68cd408d06fd: Pull complete
Digest: sha256:3bf16eeeeecca9d5500e78b2741044d731fb593155a9c5a2669123478bddcd15
Status: Downloaded newer image for docker4x/logger-azure:18.03.0-ce-azure1
764f1865458b3fd1d16491498c1b2fb38c066fd3a88d0533d66313716af34dee
kick off guide container
Unable to find image 'docker4x/guide-azure:18.03.0-ce-azure1' locally
18.03.0-ce-azure1: Pulling from docker4x/guide-azure
627beaf3eaaf: Pull complete
5092c47745b1: Pull complete
b5963e9eb739: Pull complete
9ffa11a10f98: Pull complete
c5c32715214c: Pull complete
a5ff7cd3654a: Pull complete
cd94359bfd94: Pull complete
411d66981416: Pull complete
0182a89cb99b: Pull complete
394af386f92a: Pull complete
3dd71e2d8d6a: Pull complete
7cbe3c88de02: Pull complete
8c3859aeb8e8: Pull complete
d218db557df3: Pull complete
fdcecae4a349: Pull complete
a07c4cca1297: Pull complete
f0fcb48f5d05: Pull complete
9909646140ad: Pull complete
6b07829a6f60: Pull complete
63d4638f6f7b: Pull complete
2c53d3be2039: Pull complete
5d6e0d9363e6: Pull complete
aeed129c123f: Pull complete
d524db7aa4c0: Pull complete
c4926cfd7bcc: Pull complete
b8013ec57032: Pull complete
95a9b9d61e44: Pull complete
06eb0afa6401: Pull complete
d641373462b5: Pull complete
c7e76b85a805: Pull complete
9daf97fecc09: Pull complete
1a0a108693b2: Pull complete
41f00f1f1a2e: Pull complete
06c4f3f1583b: Pull complete
175831d8d23b: Pull complete
a556dd5c217d: Pull complete
Digest: sha256:5761ea982483e4817b8b49675ff7edadfd17abe8e1b63d4b3f72aa775053dd7a
Status: Downloaded newer image for docker4x/guide-azure:18.03.0-ce-azure1
d21e28ebc70e53887b74f00ae5d1b1f54e406a9297357ec99f5906909fe09c2f
kick off meta container
Unable to find image 'docker4x/meta-azure:18.03.0-ce-azure1' locally
18.03.0-ce-azure1: Pulling from docker4x/meta-azure
550fe1bea624: Already exists
b562a5af173a: Pull complete
210fda0cd0c9: Pull complete
ef5bd81a23de: Pull complete
Digest: sha256:a3093325418686d37b1bc69a7d459f0006ef6738b8636fe35b0097a2c488a962
Status: Downloaded newer image for docker4x/meta-azure:18.03.0-ce-azure1
5f36dc1a75f7947c010daf051599c6e2b13e820e428990b4deff2e36f242f791
kick off l4controller container
Unable to find image 'docker4x/l4controller-azure:18.03.0-ce-azure1' locally
18.03.0-ce-azure1: Pulling from docker4x/l4controller-azure
550fe1bea624: Already exists
0fc0a8f20349: Pull complete
016994ee6179: Pull complete
Digest: sha256:4ccdf1412206b9d3e160db9b9ec8ebe47bec2c4cabea42d7d4d2aeabf41ee9ff
Status: Downloaded newer image for docker4x/l4controller-azure:18.03.0-ce-azure1
b95d9b71b5d54d4628cf58c5c98246bfc24cf1ebee238dce8d5ca6fbb098094a
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
 It's a Manager, run setup
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Setup Swarm Manager
   PRIVATE_IP=10.0.0.5
   LEADER_IP=
Leader IP not set yet, lets try and set it.
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
   Result of attempt to create swarminfo table: 1
 Error is normal, it is because we already have a swarm leader, lets setup a regular manager instead.
   Joining as Swarm Manager
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
LEADER_IP=
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Leader Not ready yet, sleep for 60 seconds.
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
LEADER_IP=
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Leader Not ready yet, sleep for 60 seconds.
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
LEADER_IP=
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Leader Not ready yet, sleep for 60 seconds.
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
LEADER_IP=
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Leader Not ready yet, sleep for 60 seconds.
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
LEADER_IP=
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
Leader Not ready yet, sleep for 60 seconds.
   LEADER_IP=
   MANAGER_TOKEN=
"docker swarm join" requires exactly 1 argument.
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT [flags]

Join a swarm as a node and/or manager
SWARM_ID:
NODE:
Can't connect to leader, sleep and try again
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
"docker swarm join" requires exactly 1 argument.
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT [flags]

Join a swarm as a node and/or manager
SWARM_ID:
NODE:
Can't connect to leader, sleep and try again
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
"docker swarm join" requires exactly 1 argument.
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT [flags]

Join a swarm as a node and/or manager
SWARM_ID:
NODE:
Can't connect to leader, sleep and try again
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
"docker swarm join" requires exactly 1 argument.
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT [flags]

Join a swarm as a node and/or manager
SWARM_ID:
NODE:
Can't connect to leader, sleep and try again
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
"docker swarm join" requires exactly 1 argument.
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT [flags]

Join a swarm as a node and/or manager
SWARM_ID:
NODE:
Can't connect to leader, sleep and try again
Get Leader IP from Azure Table
Traceback (most recent call last):
  File "/usr/bin/azureleader.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
   Successfully joined as a Swarm Manager
Install cloudstor ...
Install storage plugin
Traceback (most recent call last):
  File "/usr/bin/sakey.py", line 9, in <module>
    from azure.storage.table import TableService, Entity
ImportError: No module named table
18.03.0-ce-azure1: Pulling from docker4x/cloudstor
8bb80f59b17d: Download complete
Digest: sha256:84cb62d9fd8904f69d681af000fe82d7555944a566349c651ae7b65dc36900db
Status: Downloaded newer image for docker4x/cloudstor:18.03.0-ce-azure1
Error response from daemon: dial unix /run/docker/plugins/b0145ba2bcd93060346dfa0b4af0e7f6ac058d5eeaa8dcfa7bd79268ff3b0510/cloudstor.sock: connect: no such file or directory
#================ docker info    ===
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.81-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.784GiB
Name: swarm-manager000000
ID: JG4Y:CQBY:W4BT:DEV4:RMQN:V3XZ:R67O:SULU:ESEN:RQLE:SCWD:DE2F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

#================ docker node ls ===
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
#===================================
Complete Swarm setup
```
