### ISSUE TITLE
swarm is not initialized

### ISSUE THREAD

**Issue by scottmckenzie** [docker/for-azure#61]
### Expected behavior
After deploying the RM template the docker swarm is initialized.

### Actual behavior
Logged in to manager node and issued `docker node ls`:
> Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

### Information
Problem looks to be caused by docker4x/init-azure:17.12.1-ce-azure1:
> Get Leader IP from Azure Table
> Traceback (most recent call last):
>   File "/usr/bin/azureleader.py", line 9, in <module>
>     from azure.storage.table import TableService, Entity
> ImportError: No module named table
>  It's a Manager, run setup
> MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
> Setup Swarm Manager
>    PRIVATE_IP=10.0.0.4
>    LEADER_IP=
> Leader IP not set yet, lets try and set it.
> Traceback (most recent call last):
>   File "/usr/bin/azureleader.py", line 9, in <module>
>     from azure.storage.table import TableService, Entity
> ImportError: No module named table
>    Result of attempt to create swarminfo table: 1
>  Error is normal, it is because we already have a swarm leader, lets setup a regular manager instead.
>    Joining as Swarm Manager
> Get Leader IP from Azure Table
> Traceback (most recent call last):
>   File "/usr/bin/azureleader.py", line 9, in <module>
>     from azure.storage.table import TableService, Entity
> ImportError: No module named table
> LEADER_IP=
> MANAGER_TOKEN can't be found yet. LEADER_IP isn't set yet.
> Leader Not ready yet, sleep for 60 seconds.

### Steps to reproduce the behavior
Deploy this template: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fdownload.docker.com%2Fazure%2Fstable%2FDocker.tmpl

**Comment by scottmckenzie** [comment]
Sure enough, the table package is missing from that image:
`docker run -it docker4x/init-azure:17.12.1-ce-azure1 ls -lha /usr/lib/python2.7/site-packages/azure/storage`

According to the [repo](https://github.com/Azure/azure-storage-python):
> the table package is no longer releasing under the azure-storage namespace, please refer to cosmosdb

**Comment by scottmckenzie** [comment]
Sorry, duplicate of #55 .
